# Generated by Django 3.2 on 2021-07-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='skills_required',
        ),
        migrations.AddField(
            model_name='job',
            name='skills_required',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='skills',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='skills',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
