# Generated by Django 3.2 on 2021-07-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateskill',
            name='experience',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
